import { crashes, users } from "../config/mongoCollections.js";
import { createCrash } from "../data/crashes.js";
import { register } from "../data/users.js";
import { ObjectId } from "mongodb";

let crashesSeedData = [
  //crash 1
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-1.png"],
    source: "user",
    collisionId: "NYC-4588102",
    occurredAt: new Date("2025-11-09T17:45:00Z"),
    borough: "Manhattan",
    zipCode: 10021,
    latitude: 40.77123,
    longitude: -73.96456,
    onStreet: "E 72nd St",
    crossStreet: "Park Ave",
    offStreet: "Mid-block between Park Ave and Lexington Ave",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "T-bone collision at intersection, pedestrian struck by debris.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123456",
        vehicleType: "Sedan",
        make: "Toyota",
        model: "Camry",
        year: 2018,
        stateRegistration: "NY",
        contributingFactor1: "Driver was distracted",
        contributingFactor2: "Failure to give priority",
        damage: "Front-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front-Right",
        publicPropertyDamage: "None",
      },
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123457",
        vehicleType: "SUV",
        make: "Ford",
        model: "Explorer",
        year: 2022,
        stateRegistration: "NJ",
        contributingFactor1: "Unsafe speed",
        contributingFactor2: "None",
        damage: "Side",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NJ",
        preCrash: "Turning Left",
        pointOfImpact: "Side-Left",
        publicPropertyDamage: "Traffic Signal",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  //crash 2
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-2.png"],
    source: "user 2",
    collisionId: "NYC-4588103",
    occurredAt: new Date("2025-11-19T17:45:00Z"),
    borough: "Manhattan",
    zipCode: 10021,
    latitude: 41.77123,
    longitude: -72.96456,
    onStreet: "E 75nd St",
    crossStreet: "Park Ave",
    offStreet: "Mid-block between Park Ave and 75th street",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 2,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "T-bone collision at intersection",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-234567",
        vehicleType: "Sedan",
        make: "Honda",
        model: "Civic",
        year: 2019,
        stateRegistration: "NY",
        contributingFactor1: "Driver was looking at cell phone",
        contributingFactor2: "Didn't see other car",
        damage: "Front-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front-Right",
        publicPropertyDamage: "None",
      },
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123457",
        vehicleType: "Sedan",
        make: "Ford",
        model: "Focus",
        year: 2025,
        stateRegistration: "NJ",
        contributingFactor1: "Unsafe speed",
        contributingFactor2: "None",
        damage: "Side",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NJ",
        preCrash: "Turning Left",
        pointOfImpact: "Side-Left",
        publicPropertyDamage: "Traffic Signal",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // crash 3
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-3.png"],
    source: "user 3",
    collisionId: "NYC-4588104",
    occurredAt: new Date("2025-11-29T17:45:00Z"),
    borough: "Brooklyn",
    zipCode: 11201,
    latitude: 40.69423,
    longitude: -73.99156,
    onStreet: "Flatbush Ave",
    crossStreet: "Atlantic Ave",
    offStreet: "Mid-block between Atlantic Ave and Myrtle Ave",
    personsInjured: 3,
    personsKilled: 1,
    pedestriansInjured: 4,
    pedestriansKilled: 2,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 1,
    summary: "Head-on collision, pedestrian struck while crossing street.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-345678",
        vehicleType: "Truck",
        make: "Chevrolet",
        model: "Silverado",
        year: 2020,
        stateRegistration: "NY",
        contributingFactor1: "Driver fell asleep",
        contributingFactor2: "None",
        damage: "Front-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-456789",
        vehicleType: "Sedan",
        make: "Nissan",
        model: "Altima",
        year: 2017,
        stateRegistration: "NJ",
        contributingFactor1: "Ran red light",
        contributingFactor2: "None",
        damage: "Front-end",
        driverGender: "F",
        driverLicenseStatus: "Suspended",
        driverLicenseState: "NJ",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Crash 4
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-4.png"],
    source: "user 4",
    collisionId: "NYC-4588105",
    occurredAt: new Date("2025-12-05T14:30:00Z"),
    borough: "Queens",
    zipCode: 11375,
    latitude: 40.72823,
    longitude: -73.79456,
    onStreet: "Queens Blvd",
    crossStreet: "Main St",
    offStreet: "Mid-block between Main St and 57th Ave",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 3,
    pedestriansKilled: 1,
    cyclistsInjured: 1,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Cyclist hit by car door opening into bike lane.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-567890",
        vehicleType: "Sedan",
        make: "Hyundai",
        model: "Elantra",
        year: 2021,
        stateRegistration: "NY",
        contributingFactor1: "Driver opened door into bike lane",
        contributingFactor2: "None",
        damage: "Side-Right",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Parked",
        pointOfImpact: "Side-Right",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Crash 5
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-5.png"],
    source: "user 5",
    collisionId: "NYC-4588106",
    occurredAt: new Date("2025-02-10T09:15:00Z"),
    borough: "Bronx",
    zipCode: 10453,
    latitude: 40.84423,
    longitude: -73.86456,
    onStreet: "E 169th St",
    crossStreet: "Grand Concourse",
    offStreet: "Mid-block between Grand Concourse and Sheridan Ave",
    personsInjured: 4,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 2,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 4,
    motoristsKilled: 0,
    summary: "Multi-vehicle rear-end collision during rush hour.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-678901",
        vehicleType: "SUV",
        make: "Jeep",
        model: "Grand Cherokee",
        year: 2019,
        stateRegistration: "NY",
        contributingFactor1: "Following too closely",
        contributingFactor2: "Distracted driving",
        damage: "Rear-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Braking",
        pointOfImpact: "Rear",
        publicPropertyDamage: "None",
      },
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-789012",
        vehicleType: "Sedan",
        make: "Kia",
        model: "Optima",
        year: 2018,
        stateRegistration: "NJ",
        contributingFactor1: "Sudden stop of lead vehicle",
        contributingFactor2: "None",
        damage: "Front-end",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NJ",
        preCrash: "Braking",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Crash 6
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-6.png"],
    source: "user 6",
    collisionId: "NYC-4588107",
    occurredAt: new Date("2025-11-15T16:45:00Z"),
    borough: "Brooklyn",
    zipCode: 11212,
    latitude: 40.65523,
    longitude: -73.95056,
    onStreet: "3rd Ave",
    crossStreet: "E 6th St",
    offStreet: "Mid-block between E 6th St and 3rd Ave",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 0,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 2,
    motoristsKilled: 0,
    summary: "Multi-vehicle rear-end collision during rush hour.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-890123",
        vehicleType: "Pickup Truck",
        make: "Ram",
        model: "1500",
        year: 2020,
        stateRegistration: "NY",
        contributingFactor1: "Following too closely",
        contributingFactor2: "Distracted driving",
        damage: "Rear-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Braking",
        pointOfImpact: "Rear",
        publicPropertyDamage: "None",
      },
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-901234",
        vehicleType: "Sedan",
        make: "Volkswagen",
        model: "Jetta",
        year: 2017,
        stateRegistration: "NJ",
        contributingFactor1: "Sudden stop of lead vehicle",
        contributingFactor2: "None",
        damage: "Front-end",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NJ",
        preCrash: "Braking",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Crash 7
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-7.png"],
    source: "user 7",
    collisionId: "NYC-4588108",
    occurredAt: new Date("2025-07-20T11:30:00Z"),
    borough: "Queens",
    zipCode: 11368,
    latitude: 40.74223,
    longitude: -73.76956,
    onStreet: "Roosevelt Ave",
    crossStreet: "Jackson Heights",
    offStreet: "Mid-block between Jackson Heights and 37th Ave",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Pedestrian struck while crossing mid-block.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-012345",
        vehicleType: "Minivan",
        make: "Dodge",
        model: "Grand Caravan",
        year: 2019,
        stateRegistration: "NY",
        contributingFactor1: "Failure to yield right-of-way",
        contributingFactor2: "None",
        damage: "Front-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Crash 8
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-8.png"],
    source: "user 8",
    collisionId: "NYC-4588109",
    occurredAt: new Date("2025-11-25T09:15:00Z"),
    borough: "Manhattan",
    zipCode: 10001,
    latitude: 40.71278,
    longitude: -74.006,
    onStreet: "Wall St",
    crossStreet: "Broadway",
    offStreet: "Mid-block between Wall St and Broadway",
    personsInjured: 0,
    personsKilled: 1,
    pedestriansInjured: 0,
    pedestriansKilled: 1,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "1 killed in NYC's Chinatown when driver hits cyclist, pedestrian",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123890",
        vehicleType: "Sedan",
        make: "BMW",
        model: "5 Series",
        year: 2021,
        stateRegistration: "NY",
        contributingFactor1: "Driver lost control",
        contributingFactor2: "Speeding",
        damage: "Front-end",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
  // Additional dummy crashes (12) across boroughs
  // Crash 9 - Manhattan
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-9.png"],
    source: "user 9",
    collisionId: "NYC-4588110",
    occurredAt: new Date("2025-10-26T10:00:00Z"),
    borough: "Manhattan",
    zipCode: 10005,
    latitude: 40.706,
    longitude: -74.0086,
    onStreet: "Wall St",
    crossStreet: "Water St",
    offStreet: "Near Pier 11",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary:
      "Two people injured after a sideswipe near the financial district.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123891",
        vehicleType: "Sedan",
        make: "Honda",
        model: "Accord",
        year: 2019,
        stateRegistration: "NY",
        contributingFactor1: "Unsafe lane change",
        contributingFactor2: "None",
        damage: "Side",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Changing Lanes",
        pointOfImpact: "Side",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 10 - Bronx
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-10.png"],
    source: "user 10",
    collisionId: "NYC-4588111",
    occurredAt: new Date("2025-12-10T08:30:00Z"),
    borough: "Bronx",
    zipCode: 10453,
    latitude: 40.8484,
    longitude: -73.9065,
    onStreet: "E 169th St",
    crossStreet: "Grand Concourse",
    offStreet: "Near East 169th",
    personsInjured: 3,
    personsKilled: 0,
    pedestriansInjured: 2,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Pedestrian and motorist injured in multi-party crash.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123892",
        vehicleType: "SUV",
        make: "Ford",
        model: "Escape",
        year: 2020,
        stateRegistration: "NY",
        contributingFactor1: "Failure to yield",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 11 - Brooklyn
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-11.png"],
    source: "user 11",
    collisionId: "NYC-4588112",
    occurredAt: new Date("2025-12-08T19:15:00Z"),
    borough: "Brooklyn",
    zipCode: 11201,
    latitude: 40.6928,
    longitude: -73.9903,
    onStreet: "Atlantic Ave",
    crossStreet: "Flatbush Ave",
    offStreet: "Near Barclays Center",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 0,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Single motorist injured after rear-end collision.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123893",
        vehicleType: "Sedan",
        make: "Toyota",
        model: "Corolla",
        year: 2018,
        stateRegistration: "NY",
        contributingFactor1: "Following too closely",
        contributingFactor2: "None",
        damage: "Rear",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Braking",
        pointOfImpact: "Rear",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 12 - Queens
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-12.png"],
    source: "user 12",
    collisionId: "NYC-4588113",
    occurredAt: new Date("2025-12-05T07:45:00Z"),
    borough: "Queens",
    zipCode: 11375,
    latitude: 40.7282,
    longitude: -73.7946,
    onStreet: "Queens Blvd",
    crossStreet: "Main St",
    offStreet: "Near 57th Ave",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Pedestrian and motorist injured after intersection collision.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123894",
        vehicleType: "Hatchback",
        make: "Kia",
        model: "Rio",
        year: 2017,
        stateRegistration: "NY",
        contributingFactor1: "Ran stop sign",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 13 - Staten Island
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-13.png"],
    source: "user 13",
    collisionId: "NYC-4588114",
    occurredAt: new Date("2025-12-10T12:00:00Z"),
    borough: "Staten Island",
    zipCode: 10301,
    latitude: 40.6415,
    longitude: -74.076,
    onStreet: "Bay St",
    crossStreet: "Richmond Terrace",
    offStreet: "Near ferry terminal",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Pedestrian injured after being struck in crosswalk.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123895",
        vehicleType: "SUV",
        make: "Chevrolet",
        model: "Tahoe",
        year: 2016,
        stateRegistration: "NY",
        contributingFactor1: "Failure to yield",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 14 - Manhattan (pedestrians killed)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-14.png"],
    source: "user 14",
    collisionId: "NYC-4588115",
    occurredAt: new Date("2025-11-30T23:30:00Z"),
    borough: "Manhattan",
    zipCode: 10027,
    latitude: 40.8116,
    longitude: -73.9475,
    onStreet: "W 125th St",
    crossStreet: "Lenox Ave",
    offStreet: "Near Apollo Theater",
    personsInjured: 0,
    personsKilled: 1,
    pedestriansInjured: 0,
    pedestriansKilled: 1,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Fatal pedestrian collision late at night.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123896",
        vehicleType: "Sedan",
        make: "BMW",
        model: "3 Series",
        year: 2021,
        stateRegistration: "NY",
        contributingFactor1: "Speeding",
        contributingFactor2: "Poor visibility",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 15 - Bronx (motorists killed)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-15.png"],
    source: "user 15",
    collisionId: "NYC-4588116",
    occurredAt: new Date("2025-11-25T15:00:00Z"),
    borough: "Bronx",
    zipCode: 10458,
    latitude: 40.8321,
    longitude: -73.9057,
    onStreet: "Bronx River Ave",
    crossStreet: "E 177th St",
    offStreet: "Near park",
    personsInjured: 0,
    personsKilled: 1,
    pedestriansInjured: 0,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 1,
    summary: "Single-vehicle crash resulted in a motorist fatality.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123897",
        vehicleType: "Pickup Truck",
        make: "Dodge",
        model: "Ram",
        year: 2015,
        stateRegistration: "NY",
        contributingFactor1: "Driver lost control",
        contributingFactor2: "Speeding",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "Guardrail",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 16 - Brooklyn (pedestrians injured and motorists injured)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-16.png"],
    source: "user 16",
    collisionId: "NYC-4588117",
    occurredAt: new Date("2025-11-20T18:20:00Z"),
    borough: "Brooklyn",
    zipCode: 11215,
    latitude: 40.6643,
    longitude: -73.98,
    onStreet: "5th Ave",
    crossStreet: "9th St",
    offStreet: "Near Prospect Park",
    personsInjured: 3,
    personsKilled: 0,
    pedestriansInjured: 2,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Park-bound pedestrian struck; another motorist injured.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123898",
        vehicleType: "SUV",
        make: "Nissan",
        model: "Rogue",
        year: 2018,
        stateRegistration: "NY",
        contributingFactor1: "Driver distracted",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 17 - Queens (motorists injured)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-17.png"],
    source: "user 17",
    collisionId: "NYC-4588118",
    occurredAt: new Date("2025-11-18T09:50:00Z"),
    borough: "Queens",
    zipCode: 11101,
    latitude: 40.744,
    longitude: -73.9489,
    onStreet: "Queens Blvd",
    crossStreet: "Steinway St",
    offStreet: "Near Astoria Park",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 0,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Minor collision causing a motorist injury.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123899",
        vehicleType: "Sedan",
        make: "Hyundai",
        model: "Elantra",
        year: 2017,
        stateRegistration: "NY",
        contributingFactor1: "Distracted driving",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 18 - Staten Island (motorists injured and pedestrians injured)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-18.png"],
    source: "user 18",
    collisionId: "NYC-4588119",
    occurredAt: new Date("2025-11-15T14:10:00Z"),
    borough: "Staten Island",
    zipCode: 10310,
    latitude: 40.5865,
    longitude: -74.1496,
    onStreet: "Forest Ave",
    crossStreet: "Victory Blvd",
    offStreet: "Near community park",
    personsInjured: 2,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 1,
    motoristsKilled: 0,
    summary: "Pedestrian and motorist treated for injuries after collision.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123900",
        vehicleType: "Minivan",
        make: "Dodge",
        model: "Caravan",
        year: 2016,
        stateRegistration: "NY",
        contributingFactor1: "Failure to yield",
        contributingFactor2: "None",
        damage: "Side",
        driverGender: "F",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Turning Right",
        pointOfImpact: "Side",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 19 - Manhattan (pedestrians injured)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-19.png"],
    source: "user 19",
    collisionId: "NYC-4588120",
    occurredAt: new Date("2025-11-10T11:05:00Z"),
    borough: "Manhattan",
    zipCode: 10011,
    latitude: 40.742,
    longitude: -74.0018,
    onStreet: "7th Ave",
    crossStreet: "W 14th St",
    offStreet: "Near Union Square",
    personsInjured: 1,
    personsKilled: 0,
    pedestriansInjured: 1,
    pedestriansKilled: 0,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Pedestrian injured while crossing at busy intersection.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123901",
        vehicleType: "Sedan",
        make: "Mazda",
        model: "3",
        year: 2018,
        stateRegistration: "NY",
        contributingFactor1: "Driver inattention",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },

  // Crash 20 - Bronx (pedestrians killed)
  {
    _id: new ObjectId(),
    photos: ["/public/images/car-crash-20.png"],
    source: "user 20",
    collisionId: "NYC-4588121",
    occurredAt: new Date("2025-11-05T21:40:00Z"),
    borough: "Bronx",
    zipCode: 10451,
    latitude: 40.8175,
    longitude: -73.905,
    onStreet: "Fordham Rd",
    crossStreet: "University Ave",
    offStreet: "Near Fordham",
    personsInjured: 0,
    personsKilled: 1,
    pedestriansInjured: 0,
    pedestriansKilled: 1,
    cyclistsInjured: 0,
    cyclistsKilled: 0,
    motoristsInjured: 0,
    motoristsKilled: 0,
    summary: "Fatal pedestrian collision reported at night.",
    createdBy: null,
    createdAt: new Date(),
    vehicles: [
      {
        _id: new ObjectId(),
        vehicleId: "NYC-V-123902",
        vehicleType: "SUV",
        make: "Toyota",
        model: "RAV4",
        year: 2019,
        stateRegistration: "NY",
        contributingFactor1: "Speeding",
        contributingFactor2: "None",
        damage: "Front",
        driverGender: "M",
        driverLicenseStatus: "Licensed",
        driverLicenseState: "NY",
        preCrash: "Proceeding Straight",
        pointOfImpact: "Front",
        publicPropertyDamage: "None",
      },
    ],
    witness_reports: [],
    comments: [],
  },
];
let usersSeedData = [
  {
    userId: "seeduser",
    firstName: "Seed",
    lastName: "User",
    email: "seeduser@gmail.com",
    password: "123Abc!abc",
    gender: "male",
    city: "Hoboken",
    state: "New Jersey",
    dateofbirth: "2001-03-03",
  },
  {
    userId: "jkeepers",
    firstName: "Joseph",
    lastName: "Keepers",
    email: "jkeepers@gmail.com",
    password: "123Abc!abc",
    gender: "male",
    city: "Brooklyn",
    state: "New York",
    dateofbirth: "1999-03-03",
  },
  {
    userId: "mdiallo",
    firstName: "Mamadou",
    lastName: "Diallo",
    email: "mdiallo@gmail.com",
    password: "123Abc!abc",
    gender: "male",
    city: "Queens",
    state: "New York",
    dateofbirth: "2000-03-03",
  },
  {
    userId: "cpollefeys",
    firstName: "Cedric",
    lastName: "Pollefeys",
    email: "cpollefeys@gmail.com",
    password: "123Abc!abc",
    gender: "male",
    city: "Bronx",
    state: "New York",
    dateofbirth: "1999-03-03",
  },
  {
    userId: "latucha",
    firstName: "Lucia",
    lastName: "Atucha",
    email: "latucha@gmail.com",
    password: "123Abc!abc",
    gender: "female",
    city: "Manhattan",
    state: "New York",
    dateofbirth: "2000-03-03",
  },
];
const main = async () => {
  const crashesCollection = await crashes();
  const usersCollection = await users();

  await crashesCollection.deleteMany({});
  await usersCollection.deleteMany({});

  // register all seed users
  for (const userData of usersSeedData) {
    try {
      const result = await register(
        userData.firstName,
        userData.lastName,
        userData.userId,
        userData.email,
        userData.gender,
        userData.city,
        userData.state,
        userData.dateofbirth,
        userData.password
      );
      console.log("Registered new user: " + result.registrationCompleted);
    } catch (e) {
      console.log(e);
    }
  }

  // get all users and select one individually to assign as createdBy and source in crashes
  const allUsers = await usersCollection.find({}).toArray();
  const userObjectIdsArray = allUsers.map((user) => user._id.toString());
  
  // loop through crashesSeedData and assign createdBy and source fields randomly from userObjectIdsArray
  for (const crash of crashesSeedData) {
    try {
      const randomIndex = Math.floor(Math.random() * userObjectIdsArray.length);
      const randomUserId = userObjectIdsArray[randomIndex];
      crash.createdBy = new ObjectId(randomUserId);
      crash.source = allUsers.find(user => user._id.toString() === randomUserId).userId;
      const newCrash = await createCrash(crash.createdBy, crash);
      console.log("Added crash with id: " + newCrash._id);
    } catch (e) {
      console.log(e);      
    }
  }
  const usersInDb = await usersCollection.find({}).toArray();
  const allCrashes = await crashesCollection.find({}).toArray();
  console.log(`=> Total users added: ${usersInDb.length}`);
  console.log(`=> Total crashes added: ${allCrashes.length}`);
};

main()
  .then(() => {
    console.log("Done seeding database");
  })
  .catch((e) => {
    console.error(e);
  })
  .finally(() => {
    console.log("Closing connection to database");
    process.exit(0);
  });
